### ISSUE TITLE
[Defect] testing ASG should be span down if tests failed 

### ISSUE THREAD

**Issue by vmartsen-amplify** [amplifylitco/asiaq#158]
When the deployenator fails in the middle of deploy asiaq doesn't destroy testing ASG and AMI is not available to re-run. 
If blue-green deploy fails, testing ASG should be destroyed so it's possible to re-run the job with the same AMI

**Comment by jconstance-amplify** [comment]
To give some much needed context to this ticket, it looks like we have several boto2 calls in disco_aws.py that do not used throttled_call and can cause rate limit issues.

**Comment by aoskotsky-amplify** [comment]
I believe this is fixed
